apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rosa-cluster-create-pipeline
spec:
  description: "This pipeline creates a ROSA cluster, runs tests, and then deletes the cluster."
  params:
    - name: cluster-name
    - name: version
    - name: region
  tasks:
    - name: create-rosa-cluster
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/xinredhat/integration-test.git
          - name: revision
            value: main
          - name: pathInRepo
            value: rosa/rosa-cluster-create-task.yaml
      params:
        - name: name
          value: "$(params.cluster-name)"
        - name: version
          value: "$(params.version)"
    - name: test
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/xinredhat/integration-test.git
          - name: revision
            value: main
          - name: pathInRepo
            value: rosa/test.yaml
    - name: delete-rosa-cluster
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/xinredhat/integration-test.git
          - name: revision
            value: main
          - name: pathInRepo
            value: rosa/rosa-cluster-delete-task.yaml
      params:
        - name: name
          value: "$(params.cluster-name)"
        - name: region
          value: "$(params.region)"

      