---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: rosa-cluster-delete-task
spec:
  params:
    - name: name
      description: ocp cluster name that you want to delete
    - name: region
      description: ocp cluster region where you want to delete
  steps:
    - name: delete-cluster
      image: quay.io/redhat-pipeline-service/ci-runner:main
      env:
        - name: CLUSTER_NAME
          value: "$(params.name)"
        - name: ROSA_TOKEN
          valueFrom:
            secretKeyRef:
              name: hcp-cluster_secret
              key: "rosa_token"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: hcp-cluster_secret
              key: "aws_access_key_id"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: hcp-cluster_secret
              key: "aws_secret_access_key"
        - name: REGION
          value: "$(params.region)"
      script: |
        set -o errexit
        set -o nounset
        set -o pipefail

        # Give developers 15mins to connect to a pod and remove the file
        # if they want to investigate the failure
        failure_file="$PWD/destroy-cluster.txt"
        if [ -e "$failure_file" ]; then
            echo "Failure detected."
            echo "Delete '$failure_file' within 15 minutes to keep the cluster alive for investigation."
            echo
            echo "KUBECONFIG:"
            cat "$KUBECONFIG_DIR/config"
            echo
            echo "Connect to the ci-runner with: kubectl exec -n default --stdin --tty ci-runner -- bash"
            echo

            sleep 900
            if [ -e "$failure_file" ]; then
              echo "Failure is not being investigated, cluster will be destroyed."
            else
              echo "Failure under investigation, cluster will not be destroyed."
              exit 1
            fi
        fi

        if [[ -n "$CLUSTER_NAME"  ]]; then
            echo "[$(date +"%Y/%m/%d %H:%M:%S")] Started to destroy cluster [$CLUSTER_NAME]..."

            printf "Log in to your Red Hat account...\n"
            rosa login --token="$ROSA_TOKEN"

            # Here we just trigger the deletion of the cluster, we won't wait for it to be completely deleted
            rosa delete cluster --region "$REGION" --cluster="$CLUSTER_NAME" -y

        else
            echo "No OCP cluster need to be destroyed."
        fi

        echo "[$(date +"%Y/%m/%d %H:%M:%S")] Done"
