---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test
spec:
  params:
    - name: ocp-login-command
      type: string
  steps:
    - name: run-test
      image: quay.io/redhat-pipeline-service/ci-runner:main
      script: |
        echo "create hcp cluster"
        echo "version: $(params.ocp-login-command)"